<?php
session_start();
include '../database/db_connect.php';
//include '../auth.php';
//require_login(['qa_director']);
require_once '../mail/emails.php';
$active_nav = 'settings';

/* ── POST → Redirect ─────────────────────────────────────────── */
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $act = $_POST['form_action'] ?? '';

    /* ─── Accreditation Areas ─── */
    if ($act === 'create_area') {
        $name = $conn->real_escape_string(trim($_POST['area_name']??''));
        $code = $conn->real_escape_string(trim($_POST['area_code']??''));
        $desc = $conn->real_escape_string(trim($_POST['description']??''));
        $sort = (int)($_POST['sort_order']??0);
        if (!$name) { $m='Area name required.'; $t='e'; }
        else {
            $r = $conn->query("INSERT INTO areas (area_code,area_name,description,sort_order) VALUES ('$code','$name','$desc',$sort)");
            $m=$r?'Area added.':'Error: '.$conn->error; $t=$r?'s':'e';
        }
        header("Location: settings.php?tab=areas&msg=".urlencode($m)."&typ=$t"); exit;

    } elseif ($act === 'edit_area') {
        $id   = (int)$_POST['area_id'];
        $name = $conn->real_escape_string(trim($_POST['area_name']??''));
        $code = $conn->real_escape_string(trim($_POST['area_code']??''));
        $desc = $conn->real_escape_string(trim($_POST['description']??''));
        $sort = (int)($_POST['sort_order']??0);
        if (!$name || !$id) { $m='Area name required.'; $t='e'; }
        else {
            $conn->query("UPDATE areas SET area_code='$code',area_name='$name',description='$desc',sort_order=$sort WHERE id=$id");
            $m='Area updated.'; $t='s';
        }
        header("Location: settings.php?tab=areas&msg=".urlencode($m)."&typ=$t"); exit;

    } elseif ($act === 'delete_area') {
        $id  = (int)$_POST['area_id'];
        $cnt = (int)$conn->query("SELECT COUNT(*) c FROM documents WHERE area_id=$id AND deleted_at IS NULL")->fetch_assoc()['c'];
        if ($cnt > 0) { $m="Cannot delete: $cnt documents use this area."; $t='e'; }
        else { $conn->query("DELETE FROM areas WHERE id=$id"); $m='Area deleted.'; $t='s'; }
        header("Location: settings.php?tab=areas&msg=".urlencode($m)."&typ=$t"); exit;

    } elseif ($act === 'create_level') {
        $name  = $conn->real_escape_string(trim($_POST['level_name']??''));
        $order = (int)($_POST['level_order']??1);
        $desc  = $conn->real_escape_string(trim($_POST['description']??''));
        if (!$name) { $m='Level name required.'; $t='e'; }
        else {
            $r = $conn->query("INSERT INTO accreditation_levels (level_name,level_order,description) VALUES ('$name',$order,'$desc')");
            $m=$r?'Level added.':'Error: '.$conn->error; $t=$r?'s':'e';
        }
        header("Location: settings.php?tab=levels&msg=".urlencode($m)."&typ=$t"); exit;

    } elseif ($act === 'edit_level') {
        $id    = (int)$_POST['level_id'];
        $name  = $conn->real_escape_string(trim($_POST['level_name']??''));
        $order = (int)($_POST['level_order']??1);
        $desc  = $conn->real_escape_string(trim($_POST['description']??''));
        $conn->query("UPDATE accreditation_levels SET level_name='$name',level_order=$order,description='$desc' WHERE id=$id");
        header("Location: settings.php?tab=levels&msg=".urlencode('Level updated.')."&typ=s"); exit;

    } elseif ($act === 'delete_level') {
        $id  = (int)$_POST['level_id'];
        $cnt = (int)$conn->query("SELECT COUNT(*) c FROM documents WHERE accreditation_level_id=$id AND deleted_at IS NULL")->fetch_assoc()['c'];
        if ($cnt > 0) { $m="Cannot delete: $cnt documents use this level."; $t='e'; }
        else { $conn->query("DELETE FROM accreditation_levels WHERE id=$id"); $m='Level deleted.'; $t='s'; }
        header("Location: settings.php?tab=levels&msg=".urlencode($m)."&typ=$t"); exit;
    }
    // ── Mail config ──
    elseif ($act === 'save_mail_config') {
        $cfg_file = '../mail/config.php';
        $host     = preg_replace('/[^a-zA-Z0-9.\-]/', '', trim($_POST['smtp_host']??''));
        $port     = (int)($_POST['smtp_port']??587);
        $secure   = in_array($_POST['smtp_secure']??'',['tls','ssl','none'])?$_POST['smtp_secure']:'tls';
        $auth     = !empty($_POST['smtp_auth']) ? 'true' : 'false';
        $user     = addslashes(trim($_POST['smtp_user']??''));
        $pass     = addslashes(trim($_POST['smtp_pass']??''));
        $from     = addslashes(trim($_POST['mail_from']??''));
        $fname    = addslashes(trim($_POST['mail_from_name']??''));
        $app_url  = rtrim(addslashes(trim($_POST['app_url']??'')), '/');
        $enabled  = !empty($_POST['mail_enabled']) ? 'true' : 'false';

        $new_config = "<?php
// Auto-generated by Settings — ".date('Y-m-d H:i:s')."
define('MAIL_ENABLED',    $enabled);
define('SMTP_HOST',       '$host');
define('SMTP_PORT',       $port);
define('SMTP_SECURE',     '$secure');
define('SMTP_AUTH',       $auth);
define('SMTP_USER',       '$user');
define('SMTP_PASS',       '$pass');
define('MAIL_FROM',       '$from');
define('MAIL_FROM_NAME',  '$fname');
define('APP_NAME',        'S.I.T.A QA System');
define('APP_URL',         '$app_url');
define('OTP_EXPIRY_MINUTES',    10);
define('OTP_DIGITS',             6);
define('RESET_TOKEN_EXPIRY_MINUTES', 60);
?>\n";

        if (file_put_contents($cfg_file, $new_config)) {
            $m = 'Mail configuration saved.'; $t = 's';
        } else {
            $m = 'Could not write config file. Check file permissions on mail/config.php.'; $t = 'e';
        }
        header("Location: settings.php?tab=mail&msg=".urlencode($m)."&typ=$t"); exit;

    } elseif ($act === 'send_test_mail') {
        $test_to = trim($_POST['test_email']??'');
        if (!filter_var($test_to, FILTER_VALIDATE_EMAIL)) {
            $m = 'Please enter a valid test email address.'; $t = 'e';
        } else {
            $body = "<p style='font-size:15px;color:#444;'>This is a test email from <strong>".APP_NAME."</strong>.</p>"
                   .qa_email_box('If you received this email, your SMTP configuration is working correctly! ✓', '#ecfdf5', '#059669');
            $ok = qa_send_mail($test_to, 'Test Email — '.APP_NAME, qa_email_template('Mail Configuration Test', $body));
            $m = $ok ? "Test email sent to $test_to. Check your inbox." : 'Failed to send test email. Check SMTP settings and server logs.';
            $t = $ok ? 's' : 'e';
        }
        header("Location: settings.php?tab=mail&msg=".urlencode($m)."&typ=$t"); exit;
    }

    header("Location: settings.php"); exit;
}

/* ── Flash + Tab ─────────────────────────────────────────────── */
$message  = htmlspecialchars(urldecode($_GET['msg']??''));
$msg_type = ($_GET['typ']??'')==='e' ? 'error' : 'success';
$active_tab = in_array($_GET['tab']??'', ['areas','levels','mail']) ? $_GET['tab'] : 'areas';

$areas  = $conn->query("SELECT * FROM areas WHERE parent_id IS NULL ORDER BY sort_order,area_name");
$levels = $conn->query("SELECT * FROM accreditation_levels ORDER BY level_order,level_name");

$uid         = (int)$_SESSION['user_id'];
$notif_count = (int)$conn->query("SELECT COUNT(*) c FROM notifications WHERE user_id=$uid AND is_read=0")->fetch_assoc()['c'];
?>
<!DOCTYPE html><html lang="en"><head><title>Settings — QA System</title><?php include 'head.php'; ?>
<style>
.tab-pill{padding:8px 20px;border-radius:8px;font-size:.85rem;color:var(--muted);cursor:pointer;text-decoration:none;display:inline-block;}
.tab-pill.active{background:var(--primary);color:white;}
.tab-pill:hover:not(.active){background:var(--primary-xlight);color:var(--primary);}
</style>
</head>
<body><?php include 'sidebar.php'; ?>
<div class="main-content">
  <div class="topbar">
    <button class="sidebar-toggle" id="sidebar-toggle" aria-label="Toggle menu">
                <svg viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"/></svg>
            </button>
            <div class="topbar-title">Settings</div>
    <div class="topbar-right">
      <a href="notifications.php" class="notif-btn">
        <svg viewBox="0 0 20 20" fill="currentColor"><path d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z"/></svg>
        <?php if($notif_count>0):?><span class="notif-badge"><?=$notif_count?></span><?php endif;?>
      </a>
    </div>
  </div>
  <div class="page-body">
    <?php if($message):?>
    <div class="alert alert-<?=$msg_type?>">
      <svg viewBox="0 0 20 20" fill="currentColor"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/></svg>
      <?=$message?>
    </div>
    <?php endif;?>
    <div class="page-header"><h1 class="page-heading">System Settings</h1></div>

    <div style="display:flex;gap:4px;background:white;padding:6px;border-radius:12px;border:1px solid var(--border);margin-bottom:24px;width:fit-content;">
      <a href="?tab=areas"  class="tab-pill <?=$active_tab==='areas'?'active':''?>">📋 Accreditation Areas</a>
      <a href="?tab=levels" class="tab-pill <?=$active_tab==='levels'?'active':''?>">🏆 Accreditation Levels</a>
      <a href="?tab=mail"   class="tab-pill <?=$active_tab==='mail'?'active':''?>">✉️ Mail Settings</a>
    </div>

    <?php if($active_tab==='areas'): ?>
    <!-- ══ AREAS ══ -->
    <div style="display:grid;grid-template-columns:1fr 360px;gap:20px;">
      <div class="card">
        <div class="card-header">
          <span class="card-title">Accreditation Areas</span>
          <span class="text-sm text-muted"><?=$areas->num_rows?> areas</span>
        </div>
        <div class="table-wrapper">
          <table>
            <thead><tr><th>Code</th><th>Area Name</th><th>Description</th><th>Sort</th><th>Actions</th></tr></thead>
            <tbody>
            <?php if($areas->num_rows===0):?>
            <tr><td colspan="5"><div class="empty-state"><p>No areas yet.</p></div></td></tr>
            <?php else: while($a=$areas->fetch_assoc()):?>
            <tr>
              <td class="text-sm"><strong><?=htmlspecialchars($a['area_code']?:'—')?></strong></td>
              <td style="font-weight:500;"><?=htmlspecialchars($a['area_name'])?></td>
              <td class="text-sm text-muted"><?=htmlspecialchars(mb_substr($a['description']??'',0,60))?></td>
              <td class="text-sm text-muted"><?=(int)$a['sort_order']?></td>
              <td>
                <button class="btn btn-ghost btn-sm" onclick='openEditArea(<?=json_encode($a)?>')'>Edit</button>
                <form method="POST" style="display:inline;" class="swal-confirm-form" data-title="Confirm Delete" data-text="Delete this area?" data-icon="warning" data-confirm="Yes, Delete">
                  <input type="hidden" name="form_action" value="delete_area">
                  <input type="hidden" name="area_id" value="<?=$a['id']?>">
                  <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
              </td>
            </tr>
            <?php endwhile; endif;?>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card">
        <div class="card-header"><span class="card-title">Add Area</span></div>
        <div class="card-body">
          <form method="POST">
            <input type="hidden" name="form_action" value="create_area">
            <div class="field" style="margin-bottom:12px;"><label>Area Code</label><input type="text" name="area_code" placeholder="e.g. A1" maxlength="30"></div>
            <div class="field" style="margin-bottom:12px;"><label>Area Name *</label><input type="text" name="area_name" required placeholder="e.g. Mission and Vision"></div>
            <div class="field" style="margin-bottom:12px;"><label>Description</label><textarea name="description" rows="2" placeholder="Optional…"></textarea></div>
            <div class="field" style="margin-bottom:16px;"><label>Sort Order</label><input type="number" name="sort_order" value="0" min="0"></div>
            <button type="submit" class="btn btn-primary" style="width:100%;justify-content:center;">Add Area</button>
          </form>
        </div>
      </div>
    </div>

    <?php elseif($active_tab==='levels'): ?>
    <!-- ══ LEVELS ══ -->
    <div style="display:grid;grid-template-columns:1fr 360px;gap:20px;">
      <div class="card">
        <div class="card-header">
          <span class="card-title">Accreditation Levels</span>
          <span class="text-sm text-muted"><?=$levels->num_rows?> levels</span>
        </div>
        <div class="table-wrapper">
          <table>
            <thead><tr><th>Order</th><th>Level Name</th><th>Description</th><th>Actions</th></tr></thead>
            <tbody>
            <?php if($levels->num_rows===0):?>
            <tr><td colspan="4"><div class="empty-state"><p>No levels yet.</p></div></td></tr>
            <?php else: while($lv=$levels->fetch_assoc()):?>
            <tr>
              <td class="text-sm text-muted"><?=(int)$lv['level_order']?></td>
              <td style="font-weight:600;"><?=htmlspecialchars($lv['level_name'])?></td>
              <td class="text-sm text-muted"><?=htmlspecialchars(mb_substr($lv['description']??'',0,70))?></td>
              <td>
                <button class="btn btn-ghost btn-sm" onclick='openEditLevel(<?=json_encode($lv)?>')'>Edit</button>
                <form method="POST" style="display:inline;" class="swal-confirm-form" data-title="Confirm Delete" data-text="Delete this level?" data-icon="warning" data-confirm="Yes, Delete">
                  <input type="hidden" name="form_action" value="delete_level">
                  <input type="hidden" name="level_id" value="<?=$lv['id']?>">
                  <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                </form>
              </td>
            </tr>
            <?php endwhile; endif;?>
            </tbody>
          </table>
        </div>
      </div>
      <div class="card">
        <div class="card-header"><span class="card-title">Add Level</span></div>
        <div class="card-body">
          <form method="POST">
            <input type="hidden" name="form_action" value="create_level">
            <div class="field" style="margin-bottom:12px;"><label>Level Name *</label><input type="text" name="level_name" required placeholder="e.g. Level III"></div>
            <div class="field" style="margin-bottom:12px;"><label>Order (for sorting)</label><input type="number" name="level_order" value="1" min="1"></div>
            <div class="field" style="margin-bottom:16px;"><label>Description</label><textarea name="description" rows="2" placeholder="Optional…"></textarea></div>
            <button type="submit" class="btn btn-primary" style="width:100%;justify-content:center;">Add Level</button>
          </form>
        </div>
      </div>
    </div>
    <?php elseif($active_tab==='mail'): ?>
    <!-- ══ MAIL SETTINGS ══ -->
    <?php
    // Read current config values safely
    $cfg_host    = defined('SMTP_HOST')      ? SMTP_HOST      : 'smtp.gmail.com';
    $cfg_port    = defined('SMTP_PORT')      ? SMTP_PORT      : 587;
    $cfg_secure  = defined('SMTP_SECURE')    ? SMTP_SECURE    : 'tls';
    $cfg_auth    = defined('SMTP_AUTH')      ? SMTP_AUTH      : true;
    $cfg_user    = defined('SMTP_USER')      ? SMTP_USER      : '';
    $cfg_pass    = defined('SMTP_PASS')      ? SMTP_PASS      : '';
    $cfg_from    = defined('MAIL_FROM')      ? MAIL_FROM      : '';
    $cfg_fname   = defined('MAIL_FROM_NAME') ? MAIL_FROM_NAME : 'S.I.T.A QA System';
    $cfg_url     = defined('APP_URL')        ? APP_URL        : '';
    $cfg_enabled = defined('MAIL_ENABLED')   ? MAIL_ENABLED   : true;
    ?>
    <div style="display:grid;grid-template-columns:1fr 320px;gap:20px;align-items:start;">
      <div class="card">
        <div class="card-header"><span class="card-title">SMTP Configuration</span>
          <span class="badge badge-<?=$cfg_enabled?'approved':'rejected'?>"><?=$cfg_enabled?'Enabled':'Disabled'?></span>
        </div>
        <div class="card-body">
          <form method="POST">
            <input type="hidden" name="form_action" value="save_mail_config">
            <div class="form-row cols-2">
              <div class="field"><label>SMTP Host *</label><input type="text" name="smtp_host" value="<?=htmlspecialchars($cfg_host)?>" required placeholder="smtp.gmail.com"></div>
              <div class="field"><label>SMTP Port</label><input type="number" name="smtp_port" value="<?=(int)$cfg_port?>" min="1" max="65535"></div>
            </div>
            <div class="form-row cols-2">
              <div class="field"><label>Encryption</label>
                <select name="smtp_secure">
                  <option value="tls"  <?=$cfg_secure==='tls' ?'selected':''?>>TLS (port 587 — recommended)</option>
                  <option value="ssl"  <?=$cfg_secure==='ssl' ?'selected':''?>>SSL (port 465)</option>
                  <option value="none" <?=$cfg_secure==='none'?'selected':''?>>None (local dev only)</option>
                </select>
              </div>
              <div class="field" style="padding-top:28px;">
                <label style="display:flex;align-items:center;gap:8px;cursor:pointer;">
                  <input type="checkbox" name="smtp_auth" <?=$cfg_auth?'checked':''?> style="width:16px;height:16px;"> Use SMTP Authentication
                </label>
                <label style="display:flex;align-items:center;gap:8px;cursor:pointer;margin-top:10px;">
                  <input type="checkbox" name="mail_enabled" <?=$cfg_enabled?'checked':''?> style="width:16px;height:16px;"> Enable email sending
                </label>
              </div>
            </div>
            <div class="form-row cols-2">
              <div class="field"><label>SMTP Username</label><input type="text" name="smtp_user" value="<?=htmlspecialchars($cfg_user)?>" placeholder="your@gmail.com" autocomplete="off"></div>
              <div class="field"><label>SMTP Password / App Password</label><input type="password" name="smtp_pass" value="<?=htmlspecialchars($cfg_pass)?>" autocomplete="new-password" placeholder="Leave blank to keep current"></div>
            </div>
            <div class="form-row cols-2">
              <div class="field"><label>From Email</label><input type="email" name="mail_from" value="<?=htmlspecialchars($cfg_from)?>" placeholder="noreply@school.edu"></div>
              <div class="field"><label>From Name</label><input type="text" name="mail_from_name" value="<?=htmlspecialchars($cfg_fname)?>"></div>
            </div>
            <div class="form-row">
              <div class="field"><label>App URL (no trailing slash)</label><input type="url" name="app_url" value="<?=htmlspecialchars($cfg_url)?>" placeholder="http://yourdomain.com/qa_system"></div>
            </div>
            <button type="submit" class="btn btn-primary" style="width:100%;justify-content:center;margin-top:4px;">Save Configuration</button>
          </form>
        </div>
      </div>
      <div style="display:flex;flex-direction:column;gap:16px;">
        <div class="card">
          <div class="card-header"><span class="card-title">Send Test Email</span></div>
          <div class="card-body">
            <form method="POST">
              <input type="hidden" name="form_action" value="send_test_mail">
              <div class="field" style="margin-bottom:12px;"><label>Send test to</label><input type="email" name="test_email" placeholder="your@email.com" required></div>
              <button type="submit" class="btn btn-outline" style="width:100%;justify-content:center;">Send Test Email</button>
            </form>
          </div>
        </div>
        <div class="card">
          <div class="card-header"><span class="card-title">📋 Gmail Setup Guide</span></div>
          <div class="card-body">
            <ol style="font-size:13px;color:var(--muted);line-height:2;padding-left:18px;margin:0;">
              <li>Enable 2-Factor Auth on your Google account</li>
              <li>Go to <strong>Google Account → Security → App Passwords</strong></li>
              <li>Create an App Password for "Mail"</li>
              <li>Use that 16-char password above</li>
              <li>Host: <code>smtp.gmail.com</code>, Port: <code>587</code>, TLS</li>
            </ol>
          </div>
        </div>
        <div class="card">
          <div class="card-header"><span class="card-title">📧 Email Triggers</span></div>
          <div class="card-body">
            <ul style="font-size:13px;color:var(--muted);line-height:2.2;list-style:none;padding:0;margin:0;">
              <li>🔐 Login — OTP code on every login</li>
              <li>🔑 Forgot Password — reset link</li>
              <li>👤 New User — welcome + credentials</li>
              <li>🔒 Password Reset (by admin)</li>
              <li>📊 Account status changed</li>
              <li>✅ Document review decision</li>
              <li>📅 Submission deadline set</li>
              <li>📄 Document submitted (to QA)</li>
              <li>↩ Document resubmitted (to QA)</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <?php endif;?>
  </div>
</div>

<!-- EDIT AREA MODAL -->
<div class="modal-overlay" id="editAreaModal">
  <div class="modal" style="max-width:480px;">
    <div class="modal-header"><span class="modal-title">Edit Area</span>
      <button type="button" class="modal-close" onclick="this.closest('.modal-overlay').classList.remove('open')">✕</button>
    </div>
    <form method="POST"><input type="hidden" name="form_action" value="edit_area"><input type="hidden" name="area_id" id="ea_id">
      <div class="modal-body">
        <div class="form-row cols-2">
          <div class="field"><label>Code</label><input type="text" name="area_code" id="ea_code" maxlength="30"></div>
          <div class="field"><label>Sort Order</label><input type="number" name="sort_order" id="ea_sort" min="0"></div>
        </div>
        <div class="form-row"><div class="field"><label>Area Name *</label><input type="text" name="area_name" id="ea_name" required></div></div>
        <div class="form-row"><div class="field"><label>Description</label><textarea name="description" id="ea_desc" rows="3"></textarea></div></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline" onclick="this.closest('.modal-overlay').classList.remove('open')">Cancel</button>
        <button type="submit" class="btn btn-primary">Save Changes</button>
      </div>
    </form>
  </div>
</div>

<!-- EDIT LEVEL MODAL -->
<div class="modal-overlay" id="editLevelModal">
  <div class="modal" style="max-width:440px;">
    <div class="modal-header"><span class="modal-title">Edit Level</span>
      <button type="button" class="modal-close" onclick="this.closest('.modal-overlay').classList.remove('open')">✕</button>
    </div>
    <form method="POST"><input type="hidden" name="form_action" value="edit_level"><input type="hidden" name="level_id" id="el_id">
      <div class="modal-body">
        <div class="form-row cols-2">
          <div class="field"><label>Level Name *</label><input type="text" name="level_name" id="el_name" required></div>
          <div class="field"><label>Order</label><input type="number" name="level_order" id="el_order" min="1"></div>
        </div>
        <div class="form-row"><div class="field"><label>Description</label><textarea name="description" id="el_desc" rows="3"></textarea></div></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline" onclick="this.closest('.modal-overlay').classList.remove('open')">Cancel</button>
        <button type="submit" class="btn btn-primary">Save Changes</button>
      </div>
    </form>
  </div>
</div>

<script>
function openEditArea(a){
  document.getElementById('ea_id').value=a.id;
  document.getElementById('ea_code').value=a.area_code||'';
  document.getElementById('ea_name').value=a.area_name;
  document.getElementById('ea_desc').value=a.description||'';
  document.getElementById('ea_sort').value=a.sort_order||0;
  document.getElementById('editAreaModal').classList.add('open');
}
function openEditLevel(l){
  document.getElementById('el_id').value=l.id;
  document.getElementById('el_name').value=l.level_name;
  document.getElementById('el_order').value=l.level_order||1;
  document.getElementById('el_desc').value=l.description||'';
  document.getElementById('editLevelModal').classList.add('open');
}

// ── SweetAlert confirmations for edit modals ─────────────────
(function() {
    [
        { id: 'editAreaModal',  label: 'area'  },
        { id: 'editLevelModal', label: 'level' },
    ].forEach(function(m) {
        var modal = document.getElementById(m.id);
        if (!modal) return;
        var form = modal.querySelector('form');
        if (!form || form._swalWired) return;
        form._swalWired = true;
        var btn = form.querySelector('button[type="submit"]');
        if (btn) {
            btn.type = 'button';
            btn.addEventListener('click', function() {
                Swal.fire({
                    title: 'Save Changes?',
                    html: 'Save changes to this ' + m.label + '?',
                    icon: 'question',
                    showCancelButton: true,
                    confirmButtonText: 'Yes, Save',
                    cancelButtonText: 'Cancel',
                    reverseButtons: true, focusCancel: true,
                    customClass: { popup: 'qa-popup', confirmButton: 'qa-btn qa-btn-purple', cancelButton: 'qa-btn qa-btn-gray' },
                    buttonsStyling: false,
                }).then(function(r) {
                    if (r.isConfirmed) HTMLFormElement.prototype.submit.call(form);
                });
            });
        }
    });
})();
</script>
</body></html>
